package com.virtualfit.server.signaling.domain.classes

enum class ClassEventType {
    CLASS_STARTED, CLASS_ENDED, CLASS_KICKED, CLASS_ABANDONED, CLASS_JOINED,
    CLASS_CONTROLS_MUTE_ALL, CLASS_CONTROLS_UNMUTE_ALL, CLASS_CONTROLS_MUTE_SINGLE, CLASS_CONTROLS_UNMUTE_SINGLE
}